// lib/supabase.ts
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';
import Constants from 'expo-constants';
import { logger } from './logger';

// Database type will be generated by Supabase CLI
// For now, using any to avoid type errors
type Database = any;

// Environment variables with fallback for APK builds
// Try process.env first (works in dev), then Constants.expoConfig.extra (works in APK)
const supabaseUrl =
  process.env.EXPO_PUBLIC_SUPABASE_URL ||
  Constants.expoConfig?.extra?.supabaseUrl ||
  '';

const supabaseAnonKey =
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ||
  Constants.expoConfig?.extra?.supabaseAnonKey ||
  '';

// Validate environment variables
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ CRITICAL: Supabase environment variables are missing!');
  console.error('EXPO_PUBLIC_SUPABASE_URL:', supabaseUrl ? '✅' : '❌');
  console.error(
    'EXPO_PUBLIC_SUPABASE_ANON_KEY:',
    supabaseAnonKey ? '✅' : '❌'
  );
  console.error(
    'Constants.expoConfig?.extra?.supabaseUrl:',
    Constants.expoConfig?.extra?.supabaseUrl ? '✅' : '❌'
  );
  console.error(
    'Please check your .env file and app.json extra field, then rebuild the app.'
  );
}

// ✅ Platform-specific storage adapter
const getStorage = () => {
  if (Platform.OS === 'web') {
    // Web: Use localStorage directly
    return {
      getItem: (key: string) => {
        if (typeof window === 'undefined') return null;
        return window.localStorage.getItem(key);
      },
      setItem: (key: string, value: string) => {
        if (typeof window === 'undefined') return;
        window.localStorage.setItem(key, value);
      },
      removeItem: (key: string) => {
        if (typeof window === 'undefined') return;
        window.localStorage.removeItem(key);
      },
    };
  }
  // Mobile: Use AsyncStorage
  return AsyncStorage;
};

// Add a hard timeout to Supabase network calls so the UI doesn't get stuck in infinite loading
// (e.g. first boot, flaky network, stalled DNS, etc.).
// Also includes retry logic for network errors
const createTimeoutFetch = (timeoutMs: number): typeof fetch => {
  return async (input: RequestInfo | URL, init?: RequestInit) => {
    const maxRetries = 2; // Retry up to 2 times for network errors
    let lastError: Error | null = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      const controller =
        typeof AbortController !== 'undefined' ? new AbortController() : null;
      const signal = init?.signal ?? controller?.signal;

      let timeout: ReturnType<typeof setTimeout> | null = null;
      if (controller && !init?.signal) {
        timeout = setTimeout(() => controller.abort(), timeoutMs);
      }

      try {
        const response = await fetch(input, {
          ...(init || {}),
          signal: signal as any,
        });

        // If response is ok, return it
        if (response.ok) {
          if (timeout) clearTimeout(timeout);
          return response;
        }

        // If it's a server error (5xx), retry
        if (response.status >= 500 && attempt < maxRetries) {
          if (timeout) clearTimeout(timeout);
          // Exponential backoff: wait 100ms * (attempt + 1)
          await new Promise((resolve) =>
            setTimeout(resolve, 100 * (attempt + 1))
          );
          continue;
        }

        // For other errors, don't retry
        if (timeout) clearTimeout(timeout);
        return response;
      } catch (error: any) {
        if (timeout) clearTimeout(timeout);
        lastError = error;

        // Retry on network errors (AbortError, TypeError, etc.)
        if (
          attempt < maxRetries &&
          (error?.name === 'AbortError' ||
            error?.name === 'TypeError' ||
            error?.message?.includes('network') ||
            error?.message?.includes('fetch'))
        ) {
          // Exponential backoff: wait 100ms * (attempt + 1)
          await new Promise((resolve) =>
            setTimeout(resolve, 100 * (attempt + 1))
          );
          continue;
        }

        // If no more retries, throw the error
        throw error;
      }
    }

    // Should never reach here, but TypeScript needs it
    throw lastError || new Error('Fetch failed after retries');
  };
};

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  global: {
    fetch: createTimeoutFetch(20_000), // Increased to 20s to match callback.tsx timeout
    headers: {
      // ✅ Optimize connection reuse and performance
      Connection: 'keep-alive',
      'Keep-Alive': 'timeout=60, max=1000', // Keep connection alive for 60s, max 1000 requests
      // Enable HTTP/2 multiplexing hints
      'Accept-Encoding': 'gzip, deflate, br',
      // Optimize for mobile networks
      'Cache-Control': 'no-cache', // Always fetch fresh (we use React Query for caching)
    },
  },
  auth: {
    storage: getStorage() as any,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: Platform.OS === 'web',
    // ✅ Web-specific settings for better session handling
    ...(Platform.OS === 'web' && {
      flowType: 'pkce',
      storageKey: 'sb-auth-token',
    }),
  },
  db: {
    // Use connection pooling for better performance
    schema: 'public',
  },
});

// ============================================================================
// 🔥 NEW: SESSION MANAGEMENT FUNCTIONS
// ============================================================================

/**
 * Manually set Supabase session
 * Use this when you need to force-set a session (e.g., after login, token refresh)
 */
export async function setSupabaseSession(
  accessToken: string,
  refreshToken: string
): Promise<boolean> {
  logger.info('[Supabase] 🔧 Setting session manually', {
    hasAccessToken: !!accessToken,
    hasRefreshToken: !!refreshToken,
    timestamp: new Date().toISOString(),
  });

  try {
    const { data, error } = await supabase.auth.setSession({
      access_token: accessToken,
      refresh_token: refreshToken,
    });

    if (error) {
      logger.error('[Supabase] ❌ Failed to set session', error, {
        errorCode: error.status,
        timestamp: new Date().toISOString(),
      });
      return false;
    }

    logger.info('[Supabase] ✅ Session set successfully', {
      userId: data.user?.id,
      expiresAt: data.session?.expires_at,
      timestamp: new Date().toISOString(),
    });

    return true;
  } catch (err) {
    logger.error('[Supabase] ❌ Session set exception', err, {
      timestamp: new Date().toISOString(),
    });
    return false;
  }
}

/**
 * Check and ensure Supabase session is active
 * Returns true if session exists and is valid
 */
export async function ensureSupabaseSession(): Promise<boolean> {
  logger.info('[Supabase] 🔍 Checking session status', {
    timestamp: new Date().toISOString(),
  });

  try {
    const {
      data: { session },
      error,
    } = await supabase.auth.getSession();

    if (error) {
      logger.error('[Supabase] ❌ Failed to get session', error, {
        errorCode: error.status,
        timestamp: new Date().toISOString(),
      });
      return false;
    }

    if (!session) {
      logger.warn('[Supabase] ⚠️ No active session found', {
        timestamp: new Date().toISOString(),
      });
      return false;
    }

    const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
    const expiresIn = Math.floor((expiresAt - Date.now()) / 1000);

    logger.info('[Supabase] ✅ Active session found', {
      userId: session.user.id,
      expiresAt: new Date(expiresAt).toISOString(),
      expiresIn: `${expiresIn}s`,
      timestamp: new Date().toISOString(),
    });

    return true;
  } catch (err) {
    logger.error('[Supabase] ❌ Session check exception', err, {
      timestamp: new Date().toISOString(),
    });
    return false;
  }
}

/**
 * Refresh Supabase session
 * Call this when you detect the session might be stale
 */
export async function refreshSupabaseSession(): Promise<boolean> {
  logger.info('[Supabase] 🔄 Refreshing session', {
    timestamp: new Date().toISOString(),
  });

  try {
    const {
      data: { session },
      error,
    } = await supabase.auth.refreshSession();

    if (error) {
      logger.error('[Supabase] ❌ Failed to refresh session', error, {
        errorCode: error.status,
        timestamp: new Date().toISOString(),
      });
      return false;
    }

    if (!session) {
      logger.warn('[Supabase] ⚠️ No session after refresh', {
        timestamp: new Date().toISOString(),
      });
      return false;
    }

    logger.info('[Supabase] ✅ Session refreshed successfully', {
      userId: session.user.id,
      expiresAt: session.expires_at,
      timestamp: new Date().toISOString(),
    });

    return true;
  } catch (err) {
    logger.error('[Supabase] ❌ Session refresh exception', err, {
      timestamp: new Date().toISOString(),
    });
    return false;
  }
}

// ============================================================================
// CONNECTION PRE-WARMING
// ============================================================================

let connectionWarmed = false;
let connectionWarming = false;

export const warmSupabaseConnection = async (): Promise<void> => {
  if (connectionWarmed || connectionWarming) return;
  connectionWarming = true;

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000); // 5s timeout for pre-warm

    try {
      // First, try to establish connection with auth endpoint (lightweight)
      // This triggers DNS lookup, TCP connection, and SSL handshake
      const authUrl = `${supabaseUrl}/rest/v1/`;
      await fetch(authUrl, {
        method: 'HEAD',
        headers: {
          apikey: supabaseAnonKey,
          'Content-Type': 'application/json',
        },
        signal: controller.signal as any,
      }).catch(() => {
        // Ignore errors - we just want to establish connection
      });

      // Step 2: Perform a lightweight query to warm up the query path
      // This ensures the full stack (auth, query, connection pool) is ready
      const queryPromise = supabase.from('users').select('id').limit(0);

      const queryTimeout = new Promise((_, reject) => {
        setTimeout(() => reject(new Error('Pre-warm query timeout')), 5000);
      });

      await Promise.race([queryPromise, queryTimeout]).catch(() => {
        // Ignore errors - pre-warm is best effort
      });

      connectionWarmed = true;
      if (__DEV__) {
        console.log('✅ [Supabase] Connection pre-warmed (DNS + SSL + TCP)');
      }
    } finally {
      clearTimeout(timeout);
      connectionWarming = false;
    }
  } catch (error: any) {
    connectionWarming = false;
    // Silently fail - pre-warm is optional, app will work without it
    // Only log if it's not an abort error (expected timeout)
    if (__DEV__ && error?.name !== 'AbortError') {
      console.warn(
        '⚠️ [Supabase] Connection pre-warm failed (non-critical):',
        error
      );
    }
  }
};
