// lib/supabase.ts
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';
import Constants from 'expo-constants';

// Database type will be generated by Supabase CLI
// For now, using any to avoid type errors
type Database = any;

// Environment variables with fallback for APK builds
// Try process.env first (works in dev), then Constants.expoConfig.extra (works in APK)
const supabaseUrl =
  process.env.EXPO_PUBLIC_SUPABASE_URL ||
  Constants.expoConfig?.extra?.supabaseUrl ||
  '';

const supabaseAnonKey =
  process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ||
  Constants.expoConfig?.extra?.supabaseAnonKey ||
  '';

// Validate environment variables
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ CRITICAL: Supabase environment variables are missing!');
  console.error('EXPO_PUBLIC_SUPABASE_URL:', supabaseUrl ? '✅' : '❌');
  console.error(
    'EXPO_PUBLIC_SUPABASE_ANON_KEY:',
    supabaseAnonKey ? '✅' : '❌'
  );
  console.error(
    'Constants.expoConfig?.extra?.supabaseUrl:',
    Constants.expoConfig?.extra?.supabaseUrl ? '✅' : '❌'
  );
  console.error(
    'Please check your .env file and app.json extra field, then rebuild the app.'
  );
  // Don't throw here - let it fail gracefully so we can see the error in logs
}

// ✅ Platform-specific storage adapter
const getStorage = () => {
  if (Platform.OS === 'web') {
    // Web: Use localStorage directly
    return {
      getItem: (key: string) => {
        if (typeof window === 'undefined') return null;
        return window.localStorage.getItem(key);
      },
      setItem: (key: string, value: string) => {
        if (typeof window === 'undefined') return;
        window.localStorage.setItem(key, value);
      },
      removeItem: (key: string) => {
        if (typeof window === 'undefined') return;
        window.localStorage.removeItem(key);
      },
    };
  }
  // Mobile: Use AsyncStorage
  return AsyncStorage;
};

// Add a hard timeout to Supabase network calls so the UI doesn't get stuck in infinite loading
// (e.g. first boot, flaky network, stalled DNS, etc.).
const createTimeoutFetch = (timeoutMs: number): typeof fetch => {
  return async (input: any, init?: any) => {
    const controller =
      typeof AbortController !== 'undefined' ? new AbortController() : null;
    const signal = init?.signal ?? controller?.signal;

    let timeout: ReturnType<typeof setTimeout> | null = null;
    if (controller && !init?.signal) {
      timeout = setTimeout(() => controller.abort(), timeoutMs);
    }

    try {
      return await fetch(input, { ...(init || {}), signal });
    } finally {
      if (timeout) clearTimeout(timeout);
    }
  };
};

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  global: {
    fetch: createTimeoutFetch(15_000),
  },
  auth: {
    storage: getStorage() as any,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: Platform.OS === 'web',
    // ✅ Web-specific settings for better session handling
    ...(Platform.OS === 'web' && {
      flowType: 'pkce',
      storageKey: 'sb-auth-token',
    }),
  },
});
